services:
  frontend:
    build: ./frontend
    depends_on:
      - node
    volumes:
      - vite_dist:/app/dist
      - ./html:/app/web_pages
    command: sh -c "npm run build && chmod -R 777 /app/dist"

  node:
    build: ./node
    depends_on:
      - fastapi
    environment:
      FASTAPI_URL: http://fastapi:8000
    networks:
      - backend
    volumes:
      - ./node:/app
      - ./html/images:/app/html_images
      - ./frontend/public/images:/app/frontend_public_images
    env_file:
      - .env

  sync:
    image: alpine
    depends_on:
      - frontend
    volumes:
      - vite_dist:/app/dist
      - ./html:/app/web_pages
      - ./html/images:/app/html_images
      - ./frontend/public/images:/app/frontend_public_images
      # - ./html/images:/app/html_images
    command: sh -c "mkdir -p /app/web_pages; cp -Rpn /app/dist/* /app/web_pages/; cp -Rpn /app/frontend_public_images/* app/html_images/"

  fastapi:
    build: ./fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:            
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  vite_dist:
  postgres_data:

networks:
  backend: