services:
  node:
    build: ./node
    depends_on:
      - fastapi
    environment:
      FASTAPI_URL: http://fastapi:8000
    networks:
      - backend
    volumes:
      - ./images:/app/uploads
    env_file:
      - .env

  fastapi:
    build: ./fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:            
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    build: ./frontend
    depends_on:
      - node
    volumes:
      - ./html:/app/dist
    command: sh -c "npm run build"

volumes:
  postgres_data:

networks:
  backend: