"""rename password_hash to password_input

Revision ID: f1a159a29183
Revises: d6b5bbea086c
Create Date: 2026-03-10 09:10:24.948281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1a159a29183'
down_revision: Union[str, Sequence[str], None] = 'd6b5bbea086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_input', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'password_input')
    # ### end Alembic commands ###
